language: node_js
node_js:
  - "node"

after_success:
  - git config --global user.name "hundredpercentcoverage"
  - git config --global user.email "hundredpercentcoverage@users.noreply.github.com"
  - git remote rm origin
  - git remote add origin https://${GH_TOKEN}@github.com/HundredPercentCoverage/audio-cue-player.git
  - npm run deploy